// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActivityRecordController from "./activity_record_controller"
application.register("activity-record", ActivityRecordController)

import HeaderController from "./header_controller"
application.register("header", HeaderController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PasswordController from "./password_controller"
application.register("password", PasswordController)

import ProgressController from "./progress_controller"
application.register("progress", ProgressController)
